pipeline {
    agent any

    stages {
        stage('dryrun') {
            steps {
                sh """
                    echo "---> Dry Run stage"
                    terraform init 
                    terraform plan
                """
            }
        }
        stage('provision') {
            steps {
                sh """
                    echo "---> provision stage"
                    terraform apply --auto-approve
                """
            }
        }
        stage('destroy') {
            steps {
                sh """
                    echo "---> Destroy stage"
                    #terraform destroy --auto-approve
                """
            }
        }
    }
}
