---
# tasks file for httpd-installation
- name: Install the packages {{ packages }} for {{ dude }}
  yum:
    name: "{{ packages }}"
    state: installed
  
- name: Copy the index.html file to the location in remote machine
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restart service httpd